import XCTest
@testable import AdventOfCode

final class Day08Tests: XCTestCase {
    let testData = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    func testPart1() async throws {
        let challenge = Day08(data: testData)
        let result = await challenge.part1()
        XCTAssertEqual(String(describing: result), "14")
    }

    func testPart2() async throws {
        let challenge = Day08(data: testData)
        let result = await challenge.part2()
        XCTAssertEqual(String(describing: result), "34")
    }
}
